### ISSUE TITLE
which i need install to your dotifles work?

### ISSUE THREAD

**Issue by m1guer** [xzbdmw/nvimconfig#1]
hi man, i wanna know what i need install to your config work properly,because i'm getting a lot of errors.

**Comment by xzbdmw** [comment]
The things is, I modified quit a lot plugins code directly in my lazy directory to erase delay, may I ask why you want to try my config? If you come here for that reason, then I have a custom nvim-treesitter and lspconfig slightly modified for that

**Comment by m1guer** [comment]
just for research, i like to rewrite cfgs and use the best on them to improve mine.

**Comment by xzbdmw** [comment]
I’m afraid only my computer works no error, there are many globle variables interacting for simplicity. If you still want to try I can upload entire lazy directory🤭

**Comment by m1guer** [comment]
> I’m afraid only my computer works no error, there are many globle variables interacting for simplicity. If you still want to try I can upload entire lazy directory🤭

oh, if not gonna take your time i will appreciate it

**Comment by xzbdmw** [comment]
That made me think I should keep modifed version as fork in github, it took me quit a lot tome to optimize them someone may feel useful. btw how did you find my repo?

**Comment by m1guer** [comment]
in a post on reddit where leave your dotfiles link.

**Comment by xzbdmw** [comment]
@Miguerfi I have created a repro_ts.lua you can use to see the cmp highlighting, just paste the file and run `nvim  -u ~/.config/nvim/repro_ts.lua ~/.config/nvim/repro_ts.lua`, and make sure you have lua_ls installed on your system

https://github.com/xzbdmw/nvimconfig/blob/dev/repro_ts.lua

**Comment by m1guer** [comment]
i will do after work.
thx man!
:)

**Comment by edte** [comment]
Hello, when you use gopls to complete, will the width of the candidate window be truncated like this?

just use like `nvim  -u ~/.config/nvim/repro_ts.lua main.go`


<img width="600" alt="image" src="https://github.com/user-attachments/assets/51a275ca-33fc-4278-85cb-82701fcb9da4" />

**Comment by xzbdmw** [comment]
Yeah I do have code to truncate it https://github.com/xzbdmw/nvimconfig/blob/0a59638616b9e4df46a1b29b7f1e31b94e441c16/repro_ts.lua#L392
